# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '288694d6-ba62-455f-9c34-1deb19e86599'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName "Test" -linkedTemplateUri "https://raw.githubusercontent.com/stenroerholt/test-repo/master/CreateWebApp/linkedStorageAccount.json"'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'